repos:
    - repo: local
      hooks:
          - id: tsc
            name: TypeScript Compiler
            entry: npx tsc
            language: node
            types_or: [ts, tsx]
            pass_filenames: false
            args: []
            additional_dependencies: ["typescript@latest"]
            minimum_pre_commit_version: "0"
