const {
    COMPTOKEN_DECIMALS,
    COMPTOKEN_WALLET_SIZE,
    GLOBAL_DATA_SIZE,
    SEC_PER_DAY,
    DAILY_DISTRIBUTION_HISTORY_SIZE,
    compto_program_id_pubkey,
    comptoken_mint_pubkey,
    global_data_account_pubkey,
    interest_bank_account_pubkey,
    verified_human_ubi_bank_account_pubkey,
    future_ubi_bank_account_pubkey,
    compto_transfer_hook_id_pubkey,
    compto_extra_account_metas_account_pubkey,
} = require("./lib/constants.js");

const {
    Token,
    TokenAccount,
    UserData,
    UserDataAccount,
    getComptokenBalance,
    getNominalOwner,
    getDistributionOwed,
    getLastPayoutDate,
    getDaysSinceLastPayout,
    isVerifiedHuman,
    getValidBlockhashes,
    getHistoricDistributions,
    GlobalData,
    GlobalDataAccount,
} = require("./lib/accounts.js");

const {
    ComptokenProof,
    Instruction,
    createProofSubmissionInstruction,
    createCreateUserDataAccountInstruction,
    createDailyDistributionEventInstruction,
    createGetValidBlockhashesInstruction,
    createGetOwedComptokensInstruction,
    createGrowUserDataAccountInstruction,
    createVerifyHumanInstruction,
} = require("./lib/instruction.js");



module.exports = {
    Token, // accounts.js
    TokenAccount,
    UserData,
    UserDataAccount,
    getComptokenBalance,
    getNominalOwner,
    getDistributionOwed,
    getLastPayoutDate,
    getDaysSinceLastPayout,
    isVerifiedHuman,
    getValidBlockhashes,
    getHistoricDistributions,
    GlobalData,
    GlobalDataAccount,
    COMPTOKEN_DECIMALS, // constants.js
    COMPTOKEN_WALLET_SIZE,
    GLOBAL_DATA_SIZE,
    SEC_PER_DAY,
    DAILY_DISTRIBUTION_HISTORY_SIZE,
    compto_program_id_pubkey,
    comptoken_mint_pubkey,
    global_data_account_pubkey,
    interest_bank_account_pubkey,
    verified_human_ubi_bank_account_pubkey,
    future_ubi_bank_account_pubkey,
    compto_transfer_hook_id_pubkey,
    compto_extra_account_metas_account_pubkey,
    ComptokenProof, // instruction.js
    Instruction,
    createProofSubmissionInstruction,
    createCreateUserDataAccountInstruction,
    createDailyDistributionEventInstruction,
    createGetValidBlockhashesInstruction,
    createGetOwedComptokensInstruction,
    createGrowUserDataAccountInstruction,
    createVerifyHumanInstruction,
};